version: '3'
services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_FLASK_IP: localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    build:
      context: ./mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
